spring:
  name: gestione-ordini
  datasource:
    url: jdbc:mysql://localhost:3306/gestione_ordini?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Kenpachi92#
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #none
    show-sql: true
